name: Testes Jest

on:
  push:
    branches:
      - main
jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositório
        uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependências
        run: yarn install

      - name: Executar testes
        id: run-tests
        run: yarn test

  manual-approval:
      needs: run-tests
      if: failure()
      runs-on: ubuntu-latest
      timeout-minutes: 2
      steps:
        - uses: trstringer/manual-approval@v1
          with:
            secret: ${{ github.TOKEN }}
            approvers: alifcflores
            minimum-approvals: 1
            issue-title: "Testes Resultaram em Falha - Necessário sua Aprovação Manual"
            issue-body: "Revise o resultado dos testes manualmente e Aprove respondendo 'Approved' ou cancele o seguimento do pipeline respondendo 'Denied'"
            exclude-workflow-initiator-as-approver: false
            additional-approved-words: 'Approved'
            additional-denied-words: 'Denied!'

  upload-artifacts:
      needs: manual-approval
      runs-on: ubuntu-latest
      steps:
        - name: Upload dos resultados como artefato
          # if: always() && failure()
          uses: actions/upload-artifact@v2
          with:
            name: test-results
            path: ${{ github.workspace }}/jest-results.json
