name: Fluxo de Trabalho com Decisão Manual

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Verificar mudanças no diretório 'src'
      run: |
        if [[ $(git diff --name-only ${{ github.event.before }} ${{ github.sha }}) == *"src/"* ]]; then
          echo "Mudanças foram feitas no diretório 'src'."
          echo "Agora você pode acionar uma decisão manual."
          touch changes_in_src.txt
        else
          echo "Não há mudanças no diretório 'src'."
        fi

  decisao_manual:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.event_name != 'pull_request'
    
    steps:
    - name: Decisão Manual
      id: decisao_manual
      uses: actions/github-script@v5
      with:
        script: |
          const response = await github.repos.createDispatchEvent({
            owner: context.repo.owner,
            repo: context.repo.repo,
            event_type: 'manual-decision',
            client_payload: {
              message: 'Por favor, tome uma decisão manual.'
            }
          });
          console.log(response);

  acao_condicional:
    runs-on: ubuntu-latest
    needs: decisao_manual
    if: github.event_name == 'repository_dispatch' && github.event.client_payload.message == 'Por favor, tome uma decisão manual.'

    steps:
    - name: Ação Condicional
      run: echo "Executando ação condicional após decisão manual."
