name: Fluxo de Trabalho com Aprovação Manual

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Verificar mudanças no diretório 'src'
      run: |
        if [[ $(git diff --name-only ${{ github.event.before }} ${{ github.sha }}) == *"src/"* ]]; then
          echo "Mudanças foram feitas no diretório 'src'."
          echo "Agora você pode aguardar aprovação manual."
          touch changes_in_src.txt
        else
          echo "Não há mudanças no diretório 'src'."
        fi

  aguardar_aprovacao:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.event_name != 'pull_request'
    
    steps:
    - name: Aprovação Manual
      id: aprovacao
      run: echo "Aguardando aprovação manual. Adicione o rótulo 'aprovado' para continuar."
  
  acao_condicional:
    runs-on: ubuntu-latest
    needs: aguardar_aprovacao
    if: contains(github.event.issue.labels.*.name, 'aprovado')

    steps:
    - name: Ação Condicional
      run: echo "Executando ação condicional após aprovação manual."
